### ISSUE TITLE
QQ shows version 0.15.0 when using 0.1.6

### ISSUE THREAD

**Issue by fermuch** [JFryy/qq#12]
Hello and congrats on making such a useful tool!

In the [cli](https://github.com/JFryy/qq/blob/91c423f71cc43cb29a561cdce7ae20ddc179051c/cli/qq.go#L28) there's still the older version. Maybe you forgot to bump it?

**Comment by JFryy** [comment]
Yeah, I’m going to adjust it in next patch to more clearly link the version to release no. so I don’t make a mistake there again. 🤦

**Comment by JFryy** [comment]
Going to bundle in a version fix and some form of mgmt of it w. an actual feature change

**Comment by JFryy** [comment]
Hi @fermuch that is awesome thanks so much I'll need to give the AUR package an install sometime! I can link this in the readme re. the AUR package install or also feel free to make a pr regarding instructions if you want. PKGBuild looks good to me too.
