### ISSUE TITLE
`brew install qq` takes forever to get to just `0.03%`

### ISSUE THREAD

**Issue by vassudanagunta** [JFryy/qq#6]
I tried installing it with brew. The formula tries to download `https://dldir1.qq.com/qqfile/qq/QQNT/Mac/QQ_6.9.38_240617_01.dmg` and it takes forever to get to just `0.03%`.

I've never seen this on a homebrew install before. It also makes me nervous that it is installing from a close-source website rather than from a public repo on github or a vetted cached artifact hosted by homebrew. (I'm no expert on homebrew. It's just how I'd expect it to work.

**Comment by JFryy** [comment]
That looks like tencent’s qq. I haven’t pushed a forumulae or anything to aur but will this weekend.

**Comment by vassudanagunta** [comment]
Sure, i didn't think to first run `brew desc qq` to see if it was yours. I had already installed `jq` through brew so it was the first thing I tried. I prefer it because it's easy to automatically track new releases with `brew outdated`.

**Comment by JFryy** [comment]
No worries, i'll make a tap for this tomorrow, tried push to homebrew core but based on the automation and strict guidelines, it'll be easier long term just to maintain a tap for me. Have definitely slacked a bit on getting this on brew and aur.

**Comment by JFryy** [comment]
You should now be able to get this via homebrew via brew install jfryy/tap/qq (at least I can confirm this on my linux amd64 setup but the binaries should be there for arm. README is updated in #8
