### ISSUE TITLE
Make Docker Build Multi Arch

### ISSUE THREAD

**Issue by snowsky** [JFryy/qq#7]
Can you please build docker image for Mac M1 so the example can run:
```
$ echo '{"foo":"bar"}' | docker run -i jfryy/qq '.foo = "bazz"' -o tf
Unable to find image 'jfryy/qq:latest' locally
docker: Error response from daemon: no match for platform in manifest: not found.
See 'docker run --help'.
```

**Comment by JFryy** [comment]
Hey sure thing, will make the docker build multi-arch. You should now be able to get this via homebrew via `brew install jfryy/tap/qq` (at least I can confirm this on my linux amd64 setup but the binaries should be there for arm.

**Comment by JFryy** [comment]
fixed with #9, and [latest includes both archs](https://hub.docker.com/layers/jfryy/qq/latest/images/sha256-81e12aec37da304eda5555d054865890289d75c183bbf1a012966a47da3cdd11?context=repo).

**Comment by JFryy** [comment]
I haven't tested this on a m1, so if you'd like to reopen if it still has issues on a fresh pull, I'd appreciate it.

**Comment by snowsky** [comment]
Tested, It works on M1, thanks!
